#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Create config dir if not present
if [[ ! -d "${PWD}/config" ]]; then
    mkdir -p "${PWD}/config"
fi

if [[ ! -f "${PWD}/config/.HA_VERSION" ]]; then
    hass --config "${PWD}/config" --script ensure_config
fi

cp "${PWD}/.devcontainer/configuration.yaml" "${PWD}/config/configuration.yaml"

# Set the path to custom_components
## This lets us have the structure we want <root>/custom_components/allegro
## while at the same time have Home Assistant configuration inside <root>/config
## without resulting to symlinks.
export PYTHONPATH="${PYTHONPATH}:${PWD}/custom_components"

# Start Home Assistant
hass --config "${PWD}/config" --debug
